version: "3"
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: flask_db
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
volumes:
  mysql_data: